export const drugData = [
  {
    id: "d_0001",
    name: "Ibuprofen",
    other_names: ["Advil", "Motrin"],
    desc: "A nonsteroidal anti-inflammatory drug (NSAID) used to relieve pain and reduce inflammation.",
    categories: ["c_0001"],
    molecular_formula: "C13H18O2",
    sounds: [
      { gender: "female", file: "Ibuprofen - female.wav" },
      { gender: "male", file: "Ibuprofen 1 - male.wav" },
    ],
  },
  {
    id: "d_0016",
    name: "Celecoxib",
    other_names: ["Celebrex"],
    desc: "A selective COX-2 inhibitor used to relieve pain and inflammation.",
    categories: ["c_0001"],
    molecular_formula: "C17H14F3N3O2S",
    sounds: [
      { gender: "female", file: "Celecoxib - female.wav" },
      { gender: "male", file: "Celecoxib 1 - male.wav" },
    ],
  },
  {
    id: "d_0017",
    name: "Chloramphenicol",
    other_names: [],
    desc: "A broad-spectrum antibiotic used to treat serious bacterial infections.",
    categories: ["c_0002"],
    molecular_formula: "C11H12Cl2N2O5",
    sounds: [
      { gender: "female", file: "Chloramphenicol - female.wav" },
      { gender: "male", file: "Chloramphenicol 1 - male.wav" },
    ],
  },
  {
    id: "d_0018",
    name: "Diphenoxylate",
    other_names: ["Lomotil"],
    desc: "An anti-diarrheal medication used to treat severe diarrhea.",
    categories: ["c_0005"],
    molecular_formula: "C30H32N2O2",
    sounds: [
      { gender: "female", file: "Diphenoxylate - female.wav" },
      { gender: "male", file: "Diphenoxylate 1 - male.wav" },
    ],
  },
  {
    id: "d_0019",
    name: "Famciclovir",
    other_names: [],
    desc: "An antiviral drug used to treat herpes infections.",
    categories: ["c_0006"],
    molecular_formula: "C14H19N5O4",
    sounds: [
      { gender: "female", file: "Famciclovir - female.wav" },
      { gender: "male", file: "Famciclovir 1 - male.wav" },
    ],
  },
  {
    id: "d_0020",
    name: "Fluconazole",
    other_names: ["Diflucan"],
    desc: "An antifungal medication used to treat yeast infections.",
    categories: ["c_0006"],
    molecular_formula: "C13H12F2N6O",
    sounds: [
      { gender: "female", file: "Fluconazole - female.wav" },
      { gender: "male", file: "Fluconazole 1 - male.wav" },
    ],
  },
  {
    id: "d_0021",
    name: "Glyceryl trinitrate",
    other_names: ["Nitroglycerin"],
    desc: "A medication used to treat angina and heart-related conditions.",
    categories: ["c_0003"],
    molecular_formula: "C3H5N3O9",
    sounds: [
      { gender: "female", file: "Glyceryl trinitrate - female.wav" },
      { gender: "male", file: "Glyceryl trinitrate 1 - male.wav" },
    ],
  },
  {
    id: "d_0022",
    name: "Hydrocortisone",
    other_names: [],
    desc: "A corticosteroid used to treat inflammation and adrenal insufficiency.",
    categories: ["c_0009"],
    molecular_formula: "C21H30O5",
    sounds: [
      { gender: "female", file: "Hydrocortisone - female.wav" },
      { gender: "male", file: "Hydrocortisone 1 - male.wav" },
    ],
  },
  {
    id: "d_0023",
    name: "Levonorgestrel",
    other_names: [],
    desc: "A hormonal medication used for emergency contraception.",
    categories: ["c_0007"],
    molecular_formula: "C21H28O2",
    sounds: [
      { gender: "female", file: "Levonorgestrel - female.wav" },
      { gender: "male", file: "Levonorgestrel 1 - male.wav" },
    ],
  },
  {
    id: "d_0024",
    name: "Melatonin",
    other_names: [],
    desc: "A hormone supplement used to regulate sleep cycles.",
    categories: ["c_0007"],
    molecular_formula: "C13H16N2O2",
    sounds: [
      { gender: "female", file: "Melatonin - female.wav" },
      { gender: "male", file: "Melatonin 1 - male.wav" },
    ],
  },
  {
    id: "d_0025",
    name: "Naloxone",
    other_names: [],
    desc: "A medication used to reverse opioid overdose.",
    categories: ["c_0001"],
    molecular_formula: "C19H21NO4",
    sounds: [
      { gender: "female", file: "Naloxone - female.wav" },
      { gender: "male", file: "Naloxone 1 - male.wav" },
    ],
  },
  {
    id: "d_0026",
    name: "Pantoprazole",
    other_names: ["Protonix"],
    desc: "A proton pump inhibitor used to treat acid reflux.",
    categories: ["c_0005"],
    molecular_formula: "C16H15F2N3O4S",
    sounds: [
      { gender: "female", file: "Pantoprazole - female.wav" },
      { gender: "male", file: "Pantoprazole 1 - male.wav" },
    ],
  },
  {
    id: "d_0027",
    name: "Paracetamol",
    other_names: ["Acetaminophen"],
    desc: "A medication used to relieve pain and reduce fever.",
    categories: ["c_0001"],
    molecular_formula: "C8H9NO2",
    sounds: [
      { gender: "female", file: "Paracetamol - female.wav" },
      { gender: "male", file: "Paracetamol 1 - male.wav" },
    ],
  },
  {
    id: "d_0028",
    name: "Promethazine",
    other_names: [],
    desc: "An antihistamine used to treat allergies and nausea.",
    categories: ["c_0008"],
    molecular_formula: "C17H20N2S",
    sounds: [
      { gender: "female", file: "Promethazine - female.wav" },
      { gender: "male", file: "Promethazine 1 - male.wav" },
    ],
  },
  {
    id: "d_0029",
    name: "Pseudoephedrine",
    other_names: [],
    desc: "A decongestant used to relieve nasal congestion.",
    categories: ["c_0008"],
    molecular_formula: "C10H15NO",
    sounds: [
      { gender: "female", file: "Pseudoephedrine - female.wav" },
      { gender: "male", file: "Pseudoephedrine 1 - male.wav" },
    ],
  },
  {
    id: "d_0030",
    name: "Salbutamol",
    other_names: ["Albuterol"],
    desc: "A bronchodilator used to treat asthma and breathing disorders.",
    categories: ["c_0008"],
    molecular_formula: "C13H21NO3",
    sounds: [
      { gender: "female", file: "Salbutamol - female.wav" },
      { gender: "male", file: "Salbutamol 1 - male.wav" },
    ],
  },
  {
    id: "d_0031",
    name: "Sumatriptan",
    other_names: [],
    desc: "A medication used to treat migraines.",
    categories: ["c_0001"],
    molecular_formula: "C14H21N3O2S",
    sounds: [
      { gender: "female", file: "Sumatriptan - female.wav" },
      { gender: "male", file: "Sumatriptan 1 - male.wav" },
    ],
  },
  {
    id: "d_0032",
    name: "Terbutaline",
    other_names: [],
    desc: "A bronchodilator used to treat asthma and bronchospasm.",
    categories: ["c_0008"],
    molecular_formula: "C12H19NO3",
    sounds: [
      { gender: "female", file: "Terbutaline - female.wav" },
      { gender: "male", file: "Terbutaline 1 - male.wav" },
    ],
  },
  {
    id: "d_0033",
    name: "Triamcinolone",
    other_names: [],
    desc: "A corticosteroid used to treat inflammation and allergies.",
    categories: ["c_0009"],
    molecular_formula: "C21H27FO6",
    sounds: [
      { gender: "female", file: "Triamcinolone - female.wav" },
      { gender: "male", file: "Triamcinolone 1 - male.wav" },
    ],
  },
  {
    id: "d_0034",
    name: "Ulipristal",
    other_names: [],
    desc: "A medication used for emergency contraception and fibroid treatment.",
    categories: ["c_0007"],
    molecular_formula: "C30H37NO4",
    sounds: [
      { gender: "female", file: "Ulipristal - female.wav" },
      { gender: "male", file: "Ulipristal 1 - male.wav" },
    ],
  },
  {
    id: "d_0035",
    name: "Dihydrocodeine",
    other_names: [],
    desc: "An opioid analgesic used to treat moderate to severe pain and, in some cases, to relieve breathlessness and coughing.",
    categories: ["c_0001"],
    molecular_formula: "C18H23NO3",
    sounds: [{ gender: "female", file: "Dihydrocodeine - female.wav" }],
  },
  {
    id: "d_0036",
    name: "Doxylamine",
    other_names: [],
    desc: "An antihistamine primarily used as a short-term sedative for treating insomnia and, in combination with other drugs, to alleviate cold and allergy symptoms.",
    categories: ["c_0011"],
    molecular_formula: "C17H22N2O",
    sounds: [{ gender: "female", file: "Doxylamine - female.wav" }],
  },
  {
    id: "d_0037",
    name: "Metoclopramide",
    other_names: [],
    desc: "An antiemetic and prokinetic agent used to treat nausea, vomiting, and gastroparesis, and to facilitate gastric emptying.",
    categories: ["c_0010", "c_0005"],
    molecular_formula: "C14H22ClN3O2",
    sounds: [{ gender: "female", file: "Metoclopramide - female.wav" }],
  },
  {
    id: "d_0038",
    name: "Prochlorperazine",
    other_names: [],
    desc: "An antiemetic and antipsychotic medication used to control severe nausea and vomiting, and to treat schizophrenia.",
    categories: ["c_0010"],
    molecular_formula: "C20H24ClN3S",
    sounds: [{ gender: "female", file: "Prochlorperazine - female.wav" }],
  },
];

export const drugCategory = {
  c_0001: {
    id: "c_0001",
    name: "Pain Relievers",
    description: "Drugs used to relieve pain and inflammation.",
  },
  c_0002: {
    id: "c_0002",
    name: "Antibiotics",
    description: "Drugs used to treat bacterial infections.",
  },
  c_0003: {
    id: "c_0003",
    name: "Cardiovascular Drugs",
    description:
      "Drugs used to treat heart-related conditions and blood pressure issues.",
  },
  c_0004: {
    id: "c_0004",
    name: "Diabetes Medications",
    description: "Drugs used to manage diabetes and blood sugar levels.",
  },
  c_0005: {
    id: "c_0005",
    name: "Gastrointestinal Drugs",
    description: "Drugs used to treat digestive system conditions.",
  },
  c_0006: {
    id: "c_0006",
    name: "Antifungals",
    description: "Drugs used to treat fungal infections.",
  },
  c_0007: {
    id: "c_0007",
    name: "Hormonal Medications",
    description: "Drugs used for hormonal treatments and contraceptives.",
  },
  c_0008: {
    id: "c_0008",
    name: "Respiratory Medications",
    description: "Drugs used to treat asthma and other respiratory conditions.",
  },
  c_0009: {
    id: "c_0009",
    name: "Corticosteroids",
    description: "Drugs used to reduce inflammation and immune responses.",
  },
  c_0010: {
    id: "c_0010",
    name: "Antiemetics",
    description: "Drugs used to prevent or treat nausea and vomiting.",
  },
  c_0011: {
    id: "c_0011",
    name: "Antihistamines",
    description: "Drugs used to treat allergy symptoms.",
  },
};
